version: "3.4"
services:
  php-fpm:
    build: .
    image: dynamedia/docker-php-fpm:v7.4.x
    environment:
      - USER_NAME=www-data
      - GROUP_NAME=www-data
      - USER_UID=1000
      - GROUP_GID=1000
    restart: unless-stopped
    volumes:
    - ./www/:/var/www
    networks:
     - backend

networks:
  backend:
    driver: bridge
