version: "3.4"
services:
  php-fpm:
    build: .
    image: dynamedia/docker-php-fpm:v8.0.1
    env_file:
    - .env
    restart: unless-stopped
    volumes:
    - ./www/:/var/www
    networks:
     - backend

networks:
  backend:
    driver: bridge
