version: "3.4"
services:
  php-fpm:
    build: .
    image
    env_file:
    - .env
    restart: unless-stopped
    volumes:
    - ./www/:/var/www
    networks:
      - backend

networks:
  backend:
    driver: bridge
